language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint
  - go get github.com/fzipp/gocyclo
  - go get github.com/kisielk/errcheck

install:
  - go get -t -v ./...

script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - golint $(go list ./... | grep -v /vendor/)
    - errcheck -ignoretests $(go list ./... | grep -v /vendor/)
    - gocyclo -avg -over 20 .
    - go test -race $(go list ./... | grep -v /vendor/)
    - go test -race -covermode=count -coverprofile=$HOME/profile.cov $(go list ./... | grep -v /vendor/)
    - $HOME/gopath/bin/goveralls -coverprofile=$HOME/profile.cov -service=travis-ci    